// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQkKOLeNFzMShhhea3OOsjOr-cNSar_nI',
    appId: '1:530038533528:web:0746b0f8ec78ececfc4fed',
    messagingSenderId: '530038533528',
    projectId: 'cw06-task-manager-cc972',
    authDomain: 'cw06-task-manager-cc972.firebaseapp.com',
    storageBucket: 'cw06-task-manager-cc972.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIsa0Dqnx8YWwWhdB8iqzoPS5NVCRYMy0',
    appId: '1:530038533528:android:8754537c512f57dbfc4fed',
    messagingSenderId: '530038533528',
    projectId: 'cw06-task-manager-cc972',
    storageBucket: 'cw06-task-manager-cc972.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChIRzl7t-3W6pMV1ZvBLGjHET2ud0odYk',
    appId: '1:530038533528:ios:bcc6ab835a65c007fc4fed',
    messagingSenderId: '530038533528',
    projectId: 'cw06-task-manager-cc972',
    storageBucket: 'cw06-task-manager-cc972.firebasestorage.app',
    iosBundleId: 'com.example.cw06Fixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChIRzl7t-3W6pMV1ZvBLGjHET2ud0odYk',
    appId: '1:530038533528:ios:bcc6ab835a65c007fc4fed',
    messagingSenderId: '530038533528',
    projectId: 'cw06-task-manager-cc972',
    storageBucket: 'cw06-task-manager-cc972.firebasestorage.app',
    iosBundleId: 'com.example.cw06Fixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQkKOLeNFzMShhhea3OOsjOr-cNSar_nI',
    appId: '1:530038533528:web:17b18269786a4efcfc4fed',
    messagingSenderId: '530038533528',
    projectId: 'cw06-task-manager-cc972',
    authDomain: 'cw06-task-manager-cc972.firebaseapp.com',
    storageBucket: 'cw06-task-manager-cc972.firebasestorage.app',
  );

}